name: flutter_appnexus
description: Flutter plugin for AppNexus SDK
version: 0.0.2
author: OmniNext team @ Schibsted
homepage: https://github.com/schibsted/appnexus-flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.schibsted.flutter.flutter_appnexus
    pluginClass: FlutterAppnexusPlugin
