import 'package:flutter/material.dart';

class LoadMode {
  LoadMode._();

  /// factory method to create a class [LoadWhenCreated]
  factory LoadMode.whenCreated() = LoadWhenCreated;

  /// factory method to create a class [LoadWhenTriggered]
  factory LoadMode.whenTriggered(Stream triggerLoadingAd) = LoadWhenTriggered;

  /// factory method to create a class [WhenInViewport]
  factory LoadMode.whenInViewport(Stream checkIfInViewport, int pixelOffset) = WhenInViewport;
}

/// Use this class to automatically load the ad when it's created in the native code.
///
/// Use the factory method [LoadMode.whenCreated] to create it.
///
/// Check the [WhenCreatedExample] for more info.
class LoadWhenCreated extends LoadMode {
  LoadWhenCreated() : super._();
}

/// Use this class to when you want to asynchronously load the ad via a Stream
///
/// [triggerLoadingAd] is a Stream. [BannerAdView] class listens to it and load an ad on every item passed to this Stream
///
/// Use the factory method [LoadMode.whenTriggered] to create it.
///
/// Check the [WhenTriggeredExample] for more info.
class LoadWhenTriggered extends LoadMode {
  LoadWhenTriggered(this.triggerAdLoading) : super._();

  final Stream triggerAdLoading;
}

/// Use this class to when you want to asynchronously load the ad and additionally check if it's in the viewport (+- pixelOffset).
///
/// [checkIfInViewport] pass null events, to trigger checking if the BannerAdView is in the viewport (+- pixelOffset).
/// For example, the events could be generated by a [NotificationListener], so that on every scroll, you would check if the BannerAdView is in the viewport.
/// [pixelOffset] number of pixels that is used to calculate when to load the ad. NOTE: Bear in mind, that the BannerAdView should be added to the widget tree.
/// So dynamic ListViews with a builder method could not catch -1000px offsets, because the BannerAdView is not rendered/created yet.
/// Example values:
/// If set to 0, the ad will load when the widget will enter the viewport.
/// If set to -100, the ad will load -100 px before appearing on the screen.
/// If set to 100, the ad will load when 100 px of the ad could be shown.
///
/// Use the factory method [LoadMode.whenInViewport] to create it.
///
/// Check the [WhenInViewportExample] for more info.
class WhenInViewport extends LoadMode {
  WhenInViewport(this.checkIfInViewport, this.pixelOffset) : super._();

  final Stream checkIfInViewport;
  final int pixelOffset;
}